image: Visual Studio 2017
init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
configuration: Debug
before_build:
  - dotnet restore
build:
  parallel: true
  project: AdvanceDLSupport.sln
test:
  assemblies:
    only:
      - AdvancedDLSupport.Tests.dll
      - Mono.DllMap.Tests.dll

after_test:
  - nuget install altcover -OutputDirectory altcover -Version 1.6.230
  - dotnet run --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --configuration Debug -- -i=AdvancedDLSupport.Tests\bin\Debug\netcoreapp2.0 -o=instrumented-adl -x=coverage-adl.xml --assemblyExcludeFilter=.+\.Tests --assemblyExcludeFilter=AltCover.+ --assemblyExcludeFilter=Mono\.DllMap.+
  - dotnet run --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --configuration Debug -- -i=Mono.DllMap.Tests\bin\Debug\netcoreapp2.0 -o=instrumented-mdl -x=coverage-mdl.xml --assemblyExcludeFilter=.+\.Tests --assemblyExcludeFilter=AltCover.+
  - copy /y instrumented-adl\* AdvancedDLSupport.Tests\bin\Debug\netcoreapp2.0
  - copy /y instrumented-mdl\* Mono.DllMap.Tests\bin\Debug\netcoreapp2.0
  - dotnet run --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --no-build -- runner -x "dotnet" -r "AdvancedDLSupport.Tests\bin\Debug\netcoreapp2.0" -- test AdvancedDLSupport.Tests --no-build
  - dotnet run --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --no-build -- runner -x "dotnet" -r "Mono.DllMap.Tests\bin\Debug\netcoreapp2.0" -- test Mono.DllMap.Tests --no-build
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"