image: Visual Studio 2017
init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64
  - Any CPU

before_build:
  - dotnet restore
build:
  parallel: true
  project: AdvanceDLSupport.sln
test:
  assemblies:
    only:
      - AdvancedDLSupport.Tests.dll
      - Mono.DllMap.Tests.dll

after_test:
  - cmd: scripts\appveyor-coverage.bat
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh
